### ISSUE TITLE
코드 컨벤션을 정한다

### ISSUE THREAD

**Issue by java-saeng** [woowacourse-teams/2023-emmsale#1]
구글이나 아니면 다른 것들

**Comment by java-saeng** [comment]
intellij java google style 확정
메서드 파라미터, 변수가 불변이면 final 붙이기

**Comment by java-saeng** [comment]
@Test
@DisplayName

**Comment by java-saeng** [comment]
DisplayName 형식

[에러] 쿠폰이 5장인데 6장 발급 신청을 하게 되면 IllegalArgumentException이 발생할 수 있다.
[성공] 쿠폰이 5장인데 5장 발급 신청을 할 수 있다.

**Comment by amaran-th** [comment]
- Fixture 사용 여부 - 사용한다.
- DisplayName 네이밍 규칙 - 한글
    
    ⇒ `Given-When-Then` 기반으로 아래 예시처럼
    
    - [에러] 쿠폰이 5장일 때 6장 발급 신청을 하게 되면 IllegalArgumentException이 발생할 수 있다.
    - [성공] 쿠폰이 5장일 때 5장 발급 신청을 할 수 있다.
- 테스트 메서드 네이밍 규칙 - 영문
    - 본인 재량껏
- 테스트 내부 구성은 자유
- @Nested 사용 - 편한대로
- 코드 커버리지 x
- 불변 지역변수/멤버변수 등등에 `final` 붙인다.
    - 클래스에는 안 붙임
    - 설정에서 generate 단축키 사용 시 'final’ 키워드가 포함되도록 설정하기
        
        ![image](https://github.com/woowacourse-teams/2023-emmsale/assets/81465068/90879fa1-fee4-4143-98e9-f93a435882d5)

**Comment by java-saeng** [comment]
초반 코드 컨벤션은 완료

계속해서 노션 '코드 컨벤션'에 업데이트 예정
