### ISSUE TITLE
[FEAT] 사진 없을 시 보여줄 사진 변경

### ISSUE THREAD

**Issue by ki960213** [woowacourse-teams/2023-emmsale#443]
## 📌 어떤 기능인가요?
> 추가하려는 기능에 대해 간결하게 설명해주세요

사진 없을 시 보여줄 사진 변경

할 사람이 Assigness 변경하고 하시면 됩니다.

## 예상 소요 시간
> 이슈를 완료하기까지 예상되는 소요 시간을 분 or 시간 or 일 단위로 작성해주세요.

**Comment by tmdgh1592** [comment]
앱 아이콘이 보이도록 변경 완료하였습니다.
다만, 추후에 Glide의 placeHolder는 기존 회색 화면으로 변경하여 스켈레톤 ui를 제공할 필요가 있어 보입니다.
