### ISSUE TITLE
[BUG] apk 설치 안되는 버그 

### ISSUE THREAD

**Issue by chws0508** [woowacourse-teams/2023-emmsale#465]
## 🐞 어떤 버그인가요?
apk 설치가 안되는 버그입니다.

## 🙄 어떤 상황에서 발생한 버그인가요?
apk 설치를 하면, 패키지가 잘못되어 설치하지 않았습니다. 문구가 뜨며 앱이 설치되지 않는 버그.
SplashActivity 를 구성하면서, build 설정이 잘못되어 생긴 버그인 것 같습니다.

## 예상 소요 시간
20분

**Comment by tmdgh1592** [comment]
-> SplashScreen을 도입하면서 targetSdk, compileSdkPreview를 34로 변경하면서 발생하는 문제
-> 33으로 다운그레이드하면서 해결
