### ISSUE TITLE
[BUG] 자동 로그인 안되는 문제

### ISSUE THREAD

**Issue by chws0508** [woowacourse-teams/2023-emmsale#485]
## 🐞 어떤 버그인가요?
자동 로그인이 실행이 안되요

## 🙄 어떤 상황에서 발생한 버그인가요?
로그인을 한 후에 앱을 종료하고 다시 켜도 로그인 화면이 실행된다.

## 🎁 예상 결과
로그인을 한 후에 앱을 종료하고 다시키면 바로 메인화면으로 이동한다.

## 예상 소요 시간
30분

**Comment by tmdgh1592** [comment]
버그 해결 완료하였습니다. [PR](https://github.com/woowacourse-teams/2023-emmsale/pull/487)
