### ISSUE TITLE
[BUG] 채팅창 진입 시 맨 해단으로 내려가지 않는 버그 

### ISSUE THREAD

**Issue by chws0508** [woowacourse-teams/2023-emmsale#638]
## 🐞 어떤 버그인가요?
> 처음 채팅창 진입 시, 맨 밑으로  내려가지 않는 버그

## 🙄 어떤 상황에서 발생한 버그인가요?
> 처음 채팅창 진입 시, 화면이 맨 밑으로 내려가는 것을 원해요.

**Comment by tmdgh1592** [comment]
제가 맡아서 하겠습니다.
