### ISSUE TITLE
[BUG] 최근 채팅이 키보드에 가려지는 버그

### ISSUE THREAD

**Issue by chws0508** [woowacourse-teams/2023-emmsale#639]
## 🐞 어떤 버그인가요?
>  채팅창 키보드가 올라가면, 최근 채팅이 키보드에 가려지는 버그

## 🙄 어떤 상황에서 발생한 버그인가요?
> 채팅창 키보드가 올라가면, 최근 채팅이 키보드에 가려집니다.

## 🎁 예상 결과
> 키보드가 올라오면, 채팅창도 따라 올라가야 할 것 같아요.

## 예상 소요 시간
> 1시간

**Comment by tmdgh1592** [comment]
제가 맡아서 진행하겠습니다.
