### ISSUE TITLE
[BUG] 알림이 쌓이지 않는 버그

### ISSUE THREAD

**Issue by chws0508** [woowacourse-teams/2023-emmsale#640]
## 🐞 어떤 버그인가요?
> 여러개의 알림이 올 시, 알림이 쌓이지 않고, 겹쳐서 온다, 새로운 알림을 누르면, 이전 알림이 다시 나온다. 이전 알림을 확인하려면 새로운 알림을 눌러야 한다.

## 🙄 어떤 상황에서 발생한 버그인가요?
> 여러개의 알림이 올 시, 알림이 쌓이지 않고, 겹쳐서 온다, 새로운 알림을 누르면, 이전 알림이 다시 나온다. 이전 알림을 확인하려면 새로운 알림을 눌러야 한다.

## 🎁 예상 결과
> 알림이 여러개 오면, 알림이 여러개 쌓이던지, 아니면 이전 알림이 사라지던지 해야할 것 같다

## 예상 소요 시간
> 1시간

**Comment by tmdgh1592** [comment]
제가 맡아서 수정하겠습니다.

**Comment by tmdgh1592** [comment]
문제를 해결한 [PR](https://github.com/woowacourse-teams/2023-emmsale/pull/654)
