### ISSUE TITLE
[BUG] 채팅화면에서 키보드가 입력창을 가리는 버그

### ISSUE THREAD

**Issue by chws0508** [woowacourse-teams/2023-emmsale#775]
## 🐞 어떤 버그인가요?
> 채팅화면에서 키보드가 입력창을 가리는 버그

## 🙄 어떤 상황에서 발생한 버그인가요?
> 채팅화면에서 키보드가 나타나면 입력창 살짝 가리는 버그입니다.

## 🎁 예상 결과
> 카톡을 참고하여 키보드가 입력창을 가리지 않도록 합니다.

## 예상 소요 시간
30분

**Comment by tmdgh1592** [comment]
관련 이슈(#768)가 이미 존재하므로, 해당 이슈는 close합니다.
