### ISSUE TITLE
[FEAT] 게시글 화면과 댓글 화면 UX 개선

### ISSUE THREAD

**Issue by ki960213** [woowacourse-teams/2023-emmsale#795]
## 📌 어떤 기능인가요?
> 추가하려는 기능에 대해 간결하게 설명해주세요

게시글 화면과 댓글 화면 UX 개선

## 📜 작업 상세 내용
- [x] 새로운 댓글을 작성하면 맨 아래로 스크롤 되도록 수정
- [x] 댓글 입력 및 수정란의 EditText 뷰의 텍스트 간 라인 공간 2dp 늘리기
- [x] 댓글 내용의 라인 공간 2dp 늘리기
- [x] 게시글 혹은 댓글 클릭 시 소프트 키보드 닫히게 하기
- [x] 대댓글 알림 왔을 때 알림 클릭 시 그 대댓글로 스크롤 하는 기능 구현

## 예상 소요 시간
> 이슈를 완료하기까지 예상되는 소요 시간을 분 or 시간 or 일 단위로 작성해주세요.

1일

**Comment by tmdgh1592** [comment]
- 개인적으로 채팅처럼 새로운 댓글이 달리면 아래로 스크롤 되는건 조금 부자연스러울 수도 있겠다는 생각이 들어요! 자신의 댓글은 최상단에 보여주고 자신의 댓글은 아래에서 위로 쌓이는 형태는 어떻게 생각하시나

**Comment by chws0508** [comment]
자신의 댓글이 여러개인 경우 어떡하나요??

**Comment by ki960213** [comment]
아래로 스크롤할 수 없을 때만 새로운 댓글이 달렸을 때 아래로 스크롤 된다면 새로운 댓글이 달린 것을 바로 읽을 수 있으니 괜찮지 않을까요?
댓글 화면에서 새로운 댓글이 달리면 자동으로 새로고침하는 것은 어떻게 생각하시나요?

자신의 댓글이 최상단에 보이는 건 유튜브처럼 댓글이 매우 많이 쌓일 가능성이 있을 땐 좋아보이지만 그렇지 않다면 작성된 순서대로 보여주는 게 자연스럽지 않을까요?

**Comment by tmdgh1592** [comment]
> 자신의 댓글이 여러개인 경우 어떡하나요??

위에 작성해놓긴 했는데, 자신의 댓글은 시간 순으로 아래에서 위로 쌓입니다.

```
최신 댓글
과거 댓글
더 과거 댓글
```

**Comment by tmdgh1592** [comment]
> 아래로 스크롤할 수 없을 때만 새로운 댓글이 달렸을 때 아래로 스크롤 된다면 새로운 댓글이 달린 것을 바로 읽을 수 있으니 괜찮지 않을까요?

제가 제안드린 방식은 댓글 화면에 진입했을 때 자신의 댓글을 빠르게 볼 수도 있습니다.

> 자신의 댓글이 최상단에 보이는 건 유튜브처럼 댓글이 매우 많이 쌓일 가능성이 있을 땐 **좋아보이지만**

최상단에 자신의 댓글이 보이는 UI가 댓글이 많은 경우와 그렇지 않은 경우에 어떤 차이가 있는지 궁금하네요.

**Comment by ki960213** [comment]
게시글에서 마지막 댓글에 대한 댓글을 작성해도 본인은 그것과 상관없는 위치에 있는 댓글을 보게 될 수 있기 때문입니다.
예를 들어서 누가 댓글에 특정 게시글 작성자를 비난하는 댓글을 달았을 때, 사람들에게 공개적으로 두둔하는 댓글을 보여주기 위해 작성자에 대한 옹호 댓글을 작성할 경우 작성 시간 순서대로 정렬되어 있다면 맥락을 알기 쉬울 것입니다. 대부분의 커뮤니티의 댓글 정렬 방식 또한 기본적으로 시간 순이라고 생각합니다.
하지만 유튜브는 몇 천 개씩 달리는 경우가 허다하기 때문에 이 땐 작성 시간 순으로 정렬한다면 본인의 댓글을 찾기 어려울 것입니다. 이러면 본인의 댓글의 대댓글 화면에 들어가기 힘들기 때문에 본인 댓글을 가장 위에 보여주면 좋다고 생각합니다. 저는 개인적으로 유튜브에서 누군가와 대댓글로 대화할 때는 본인의 댓글이 위에 있어서 좋았습니다.
댓글 화면에 진입했을 때 특정 댓글로 스크롤 되는 기능은 어디 화면에서 들어가느냐에 따라 다르다고 생각합니다. 알림이나 자신의 댓글 목록 화면에서 들어갔을 땐 스크롤 되면 좋지만 게시글에서 들어갔을 땐 스크롤 되지 않는 게 좋다고 생각합니다.

**Comment by ki960213** [comment]
혹시 본인이 새로운 댓글을 달았을 때 맨 아래로 스크롤 되어서 본인의 새로운 댓글을 볼 수 있도록 하는 것이 부자연스럽다고 생각하시나요?

**Comment by chws0508** [comment]
댓글이 정말 많은 경우에, 자신의 댓글을 찾기가 힘들기 때문에 최상단 UI 에 배치하는 전략을 유튜브가 사용한 것 같습니다.

만약 게시물에 들어갔을 때, 자신의 댓글이 항상 최상단에 위치한다면, 내가 댓글을 어느 시점에 작성했는지 알 수가 없을 것 같아서 그게 좀 걸리네요

**Comment by chws0508** [comment]
> 혹시 본인이 새로운 댓글을 달았을 때 맨 아래로 스크롤 되어서 본인의 새로운 댓글을 볼 수 있도록 하는 것이 부자연스럽다고 생각하시나요?

저는 이것은 찬성입니다. 다른 커뮤니티 앱도 이렇게 하고있고, 자신의 댓글이 달렸다는 것을 눈으로 확인할 수 있게 하는것이 사용자에게 좋다고 생각합니다.

**Comment by tmdgh1592** [comment]
두 분 의견을 듣고 찾아보니 대부분의 커뮤니티는 단순히 시간순으로 배치되어 있네요 🧐
커뮤니티를 잘 안 해봐서 몰랐습니다 😓

> 게시글에서 마지막 댓글에 대한 댓글을 작성해도 본인은 그것과 상관없는 위치에 있는 댓글을 보게 될 수 있기 때문입니다.

이런 문제때문에 제가 생각했었던 것은 댓글 목록에서는 자신의 댓글이 아래에서 위로, 대댓글에서는 시간순으로 정렬되는 방식을 생각했었습니다. 그런데 `댓글이 정말 많은 경우에, 자신의 댓글을 찾기가 힘들기 때문에 최상단 UI 에 배치하는 전략을 유튜브가 사용한 것 같습니다.` 라는 말을 들어보니 **댓글 목록 : 댓글이 정말 많은 경우** / **대댓글 목록 : 댓글이 별로 없는 경우** 로 연결이 되네요.

결론) 단순 시간순으로 배치해도 좋을 것 같습니다! 다만 smoothScroll만 아니면 좋겠다는 생각이에요!

**Comment by ki960213** [comment]
개인적으로 본인의 새로운 댓글을 작성했을 땐 smooth scroll이 낫다고 생각합니다. 댓글 달았을 때 맨 아래로 순간이동 한다면 어색하지 않을까요? 그리고 smooth scroll 한다면 사용자가 스크롤 하고 싶지 않다면 화면을 터치해서 스크롤을 취소할 수도 있기 때문에 본인의 새로운 댓글 작성 시엔 smooth scroll이 낫다고 생각합니다.

**Comment by chws0508** [comment]
내가 댓글 달았을 떄 => Smooth Scrol 을 통해 내가 작성한 댓글이 달렸다는 것을 보여줌
푸쉬 알림을 통해 들어갔을 때 => Normal Scroll
내가 작성한 댓글 버튼을 통해 들어갔을 때 => Normal Scroll

**Comment by tmdgh1592** [comment]
말씀하신 것처럼 댓글이 얼마 없기 때문에 smooth를 해도 사용자가 도중에 스크롤을 취소하는 경우가 얼마나 있을까 라는 생각입니다.
댓글을 달면 마치 화면이 갱신된 것처럼 바로 최하단으로 이동하는게 자연스럽다고 생각합니다.

smooth와 일반 스크롤 둘을 직접 비교해보는 것도 좋겠네요~

**Comment by tmdgh1592** [comment]
그 외에는 스캇이 작성해주신 것과 동일한 의견입니다.
