### ISSUE TITLE
[문의] 안녕하세요 지디지 송도 입니다.

### ISSUE THREAD

**Issue by yong076** [woowacourse-teams/2023-emmsale#824]
저희 모바일 앱 개발자 컨퍼런스가 해당 앱에 노출이 되고 있는데요, 삭제 부탁 드립니다.
![스크린샷 2023-11-03 오전 11 00 46](https://github.com/woowacourse-teams/2023-emmsale/assets/4486139/cd1aeffb-897d-4d88-9ab0-00cbe72e6541)

**Comment by hong-sile** [comment]
넵 확인하고 삭제했습니다.

**Comment by yong076** [comment]
궁금한게 있어서 그런데, 카카오톡 yong076 혹은 01031850969 로 문자한통만 남겨 주세요 :)
